# Generated by Django 5.0 on 2023-12-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserError',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_user', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_error',
                'ordering': ['-id'],
            },
        ),
    ]
