# Generated by Django 5.0 on 2023-12-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usererror',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
