# Generated by Django 5.0 on 2023-12-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usererror_user_a_usererror_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usererror',
            name='user_a',
        ),
    ]
